### ISSUE TITLE
Conditional ((VI4. != "A1" or VI4. != "A5"))

### ISSUE THREAD

**Issue by jrgonzalezrios** [TechoGT/survey-mobile-app#16]
In question 4 of section VI, conditional seems not to be working, it steps into question 5 in any case

**Comment by humbertn** [comment]
Sorry, but I couldn't replicate the error, would you be so kind and post an image or something that could help.

Thanks.

**Comment by humbertn** [comment]
Ok, this seems just to be a misunderstanding, the condition  ((VI4. != "A1" or VI4. != "A5")), it's always true, since you can only select one answer, so, if you want this to be effective, I suggest to change this condition to this:  ((VI4. != "A1" AND VI4. != "A5")), because with OR this will always be true with radio buttons.

If you don't have any other problem with this, please close this issue.

Thanks.
